### ISSUE TITLE
Downloading extensions with names containing illegal characters

### ISSUE THREAD

**Issue by ckykenken** [dashokkumar93/crx-download#11]
Trying to download an extension "Burner Emails: Easy, Fast, Disposable Emails", which contains illegal characters (probably ':', ','), the extension refuses to download
That extension: https://chrome.google.com/webstore/detail/burner-emails-easy-fast-d/dnnmaoecogobjdiieopljefemjdkkaja
![image](https://user-images.githubusercontent.com/26035978/135325047-6eec8ae4-e98e-4c66-9cae-d1089bd498e0.png)

**Comment by tonystark93** [comment]
@ckykenken  Hope you using the latest version of crx downloader. https://github.com/tonystark93/crx-download/blob/e2b859ad87043c81aa263d20f0e67eed6f5369ce/background.js#L40
As you can see we do sanitize the folder names to removed certain characters.

If you are using the latest version and still facing the issue. Please let us know which OS, and default language you are using(helpful in finding the root cause of the issue)

**Comment by tonystark93** [comment]
@ckykenken  The issue is fixed and updated. Please update the extension. If you are facing any issues for any particular extension url, update it here.
